### PR TITLE
Add Avro null support for System.Nullable types

### PR DESCRIPTION
**Pull request by ecarlson94**

### CODE REVIEW

**Comment by ecarlson94** [comment]
Thanks for the quick turn around.

**Comment by AdrianStrugala** [comment]
Tbh, I am playing with the code at the moment, and what I can see, System.Nullable types were automatically generating information in a schema that could contain null even before ur change. Have you maybe checked that?

**Comment by AdrianStrugala** [comment]
Or am I missing something?

**Comment by ecarlson94** [comment]
I made a mistake. I apologize.

**Comment by AdrianStrugala** [comment]
No problem :) Thanks for checking the case

**Pull request merged**
