### PR TITLE
Add support for [EnumMember] attributes

### PR DESCRIPTION
**Pull request by robertcoltheart**
This allows us to have a level of compatibility with Java enums, while still maintaining proper .NET coding standards.

It makes sense to support this, since we already support `[DataMember]`.

eg.
```c#
public enum MyEnum
{
    [EnumMember(Value = "MY_VALUE")]
    MyValue
}
```

### CODE REVIEW

**Comment by robertcoltheart** [comment]
Hi @AdrianStrugala, this is ready for review

**Comment by AdrianStrugala** [comment]
Hey Robert,
Thank you for your PR. I will try to review it in next week.
Adrian

**Comment by robertcoltheart** [comment]
Hi @AdrianStrugala, any chance you can push this out to Nuget?

**Comment by robertcoltheart** [comment]
Bump @AdrianStrugala

**Pull request merged**
